steps:
  # 1. Prepare Server Context
  # Copy shared, config, and public directories to server/ context as required by Dockerfile
  # This replicates the logic in scripts/deploy-backend.sh
  - name: 'bash'
    args:
      - '-c'
      - |
        echo "Preparing build context..."
        
        # Create destination directories
        mkdir -p server/_shared_temp
        mkdir -p server/config
        mkdir -p server/public

        # Copy shared module (contents of shared/ to server/_shared_temp/)
        # Note: In Cloud Build, we are at the root of the repo
        cp -r shared/* server/_shared_temp/
        
        # Ensure shared module is treated as ESM
        echo '{"type": "module"}' > server/_shared_temp/package.json

        # Copy config
        cp -r config/* server/config/

        # Copy public folder (for curation.js)
        cp -r public/* server/public/
        
        echo "Context prepared. Listing server/ directory:"
        ls -la server/
        ls -la server/_shared_temp/

  # 2. Build the Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mjrp-proxy:$COMMIT_SHA', '-f', 'server/Dockerfile', 'server']

  # 3. Push the Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mjrp-proxy:$COMMIT_SHA']

  # 4. Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mjrp-proxy'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mjrp-proxy:$COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/mjrp-proxy:$COMMIT_SHA'
